spring:
  datasource :
    url : jdbc:mysql://43.201.122.223:3306/bootex_ohs?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name : com.mysql.cj.jdbc.Driver
    username : hansoo
    password : Hansoo2023!
  jpa :
    database-platform : org.hibernate.dialect.MySQLDialect
    hibernate :
      #???? crate, update, create-drop, validate
      #create? ?? ??? ??? ?? ??, update? ???? ??? ???? ??? ??? ??? alter
      ddl-auto : update
    #?? JPA ???? Hibernate? ????? ???? SQL? ????? ??
    properties:
      hibernate:
        format_sql: true
    #JPA ??? ???? SQL? ??? ??? ??
    show-sql: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false
  servlet:
    multipart :
      enabled : true
      location : C:\\upload
      max-request-size: 30MB
      max-file-size: 10MB

org:
  zerock:
    upload:
      path: C:\\upload

server :
  port : 8082

logging:
  level:
    org:
      zerock: debug
      springframework:
        security:
          web: trace


